version: '2'

services:
  web:
    container_name: simplePythonFlask
    image: simplePythonFlask:latest
    port:
      - 5000:5000

  mariadb:
    container_name: mariadb
    image: mariadb:latest
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe123qwe"
    volumes:
      - mariadb_data

volumes:
  mariadb_data:
