apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb-data-pv
spec:
  capacity:
    storage: 500Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /home/vagrant/mariadb-data