name: Mudando version

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      
      - name: Configurar Docker para aceitar registries inseguros
        run: |
          echo '{"insecure-registries": ["${{ secrets.NEXUS_REGISTRY }}"] }' | sudo tee /etc/docker/daemon.json
          cat /etc/docker/daemon.json
          sudo systemctl restart docker

      - name: Login no Docker do Nexus
        run: |
          echo "${{ secrets.NEXUS_PASS }}" | docker login ${{ secrets.NEXUS_REGISTRY }} -u ${{ secrets.NEXUS_USER }} --password-stdin

      - name: Build da imagem
        run: docker build -t ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ github.run_number }} .

      - name: Push da imagem para o Nexus
        run: | 
          docker tag ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ github.run_number }} ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:latest
          docker push ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ github.run_number }}
          docker push ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:latest

      - name: Atualizar deployment.yaml com nova tag da imagem
        run: |
          sed -i "s|image: ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:.*|image: ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ github.run_number }}|" manifest/web-deployment.yaml
          sed -i "s|image: ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:.*|image: ${{ secrets.NEXUS_REGISTRY }}/${{ secrets.CONTAINER_IMAGE }}:${{ github.run_number }}|" manifest/web-initiate-db-deployment.yaml

      - name: Autenticar no Git com token pessoal
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/4emerson/course-catalog.git

      - name: Comitar e enviar mudanças
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add manifest/web-deployment.yaml manifest/web-initiate-db-deployment.yaml
          git commit -m "Atualiza a tag da imagem para ${{ github.run_number }}" || echo "Nada para commitar"
          git push
