name: K8s - Teste de conexão

on:
  workflow_dispatch:

jobs:
  get-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4

      - name: Configurar kubeconfig a partir do Secret
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_K3S }}" > ~/.kube/config
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Testar acesso ao cluster
        run: kubectl get nodes --insecure-skip-tls-verify
