name: K8s - Teste de conexão

on:
  workflow_dispatch:

jobs:
  get-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4

      - name: Criar kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBECONFIG_K3S }}" > ~/.kube/k3s.yaml
          echo "KUBECONFIG=$HOME/.kube/k3s.yaml" >> $GITHUB_ENV  # Exporta para os próximos steps

      - name: Listar nodes do cluster K3s
        run: kubectl get nodes --insecure-skip-tls-verify
