name: K8s - Teste de conexão

on:
  workflow_dispatch:

jobs:
  get-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Instalar kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'v1.24.0'
          
      - name: Configurar kubeconfig a partir do Secret
        env:
          KUBECONFIG_K3S: ${{ secrets.KUBECONFIG_K3S }}
        run: |
          mkdir ~/.kube/
          echo "$KUBECONFIG_K3S" | base64 -d > ~/.kube/config

      - name: Testar acesso ao cluster
        run: kubectl get nodes --insecure-skip-tls-verify
