name: K8s - Teste de conexão

on:
  workflow_dispatch:

jobs:
  get-nodes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v2

      - name: Kuberntes CLI - kubectl
        uses: azure/setup-kubectl@v1

      - name: Kubeconfig
        run: |
          mkdir ~/.kube
          echo "${{ secrets.KUBECONFIG_K3S }}" > ~/.kube/k3s.yaml
          export KUBECONFIG=~/.kube/k3s.yaml

      - name: Listando nodes
        run: export KUBECONFIG=~/.kube/k3s.yaml && kubectl get nodes
